/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DiasporaRouteImport } from './routes/diaspora'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsSlugRouteImport } from './routes/reports.$slug'
import { Route as UpdatesIndexRouteImport } from './routes/updates.index'
import { Route as UpdatesSlugRouteImport } from './routes/updates.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DiasporaRoute = DiasporaRouteImport.update({
  id: '/diaspora',
  path: '/diaspora',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSlugRoute = ReportsSlugRouteImport.update({
  id: '/reports/$slug',
  path: '/reports/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesIndexRoute = UpdatesIndexRouteImport.update({
  id: '/updates/',
  path: '/updates/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesSlugRoute = UpdatesSlugRouteImport.update({
  id: '/updates/$slug',
  path: '/updates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/diaspora': typeof DiasporaRoute
  '/get-involved': typeof GetInvolvedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/updates/$slug': typeof UpdatesSlugRoute
  '/reports/': typeof ReportsIndexRoute
  '/updates/': typeof UpdatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/diaspora': typeof DiasporaRoute
  '/get-involved': typeof GetInvolvedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/updates/$slug': typeof UpdatesSlugRoute
  '/reports': typeof ReportsIndexRoute
  '/updates': typeof UpdatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/diaspora': typeof DiasporaRoute
  '/get-involved': typeof GetInvolvedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/updates/$slug': typeof UpdatesSlugRoute
  '/reports/': typeof ReportsIndexRoute
  '/updates/': typeof UpdatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/diaspora'
    | '/get-involved'
    | '/sitemap.xml'
    | '/reports/$slug'
    | '/updates/$slug'
    | '/reports/'
    | '/updates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/diaspora'
    | '/get-involved'
    | '/sitemap.xml'
    | '/reports/$slug'
    | '/updates/$slug'
    | '/reports'
    | '/updates'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/diaspora'
    | '/get-involved'
    | '/sitemap.xml'
    | '/reports/$slug'
    | '/updates/$slug'
    | '/reports/'
    | '/updates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  DiasporaRoute: typeof DiasporaRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ReportsSlugRoute: typeof ReportsSlugRoute
  UpdatesSlugRoute: typeof UpdatesSlugRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  UpdatesIndexRoute: typeof UpdatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diaspora': {
      id: '/diaspora'
      path: '/diaspora'
      fullPath: '/diaspora'
      preLoaderRoute: typeof DiasporaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$slug': {
      id: '/reports/$slug'
      path: '/reports/$slug'
      fullPath: '/reports/$slug'
      preLoaderRoute: typeof ReportsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/': {
      id: '/updates/'
      path: '/updates'
      fullPath: '/updates/'
      preLoaderRoute: typeof UpdatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/$slug': {
      id: '/updates/$slug'
      path: '/updates/$slug'
      fullPath: '/updates/$slug'
      preLoaderRoute: typeof UpdatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  DiasporaRoute: DiasporaRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ReportsSlugRoute: ReportsSlugRoute,
  UpdatesSlugRoute: UpdatesSlugRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  UpdatesIndexRoute: UpdatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
